### ISSUE TITLE
Add on screen stats for few sec on layer change 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#29]
Show div with icon + metadata on the current layer activated by the toggles 
![Screen Shot 2020-04-15 at 09 24 29](https://user-images.githubusercontent.com/14296774/79342291-eceb7880-7efa-11ea-9567-4bfbf114db3b.png)

**Comment by RELNO** [comment]
@agrignard is there somewhere I can get the before/after stats for each layer?

**Comment by agrignard** [comment]
All the available metrics have been summurize in the radar plot (though we don't have the exact value printed (and Luis did a normalization also)
before
https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/includes/PNG/radar_plot/radar_plot.001.jpeg
after
https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/includes/PNG/radar_plot/radar_plot.002.jpeg

**Comment by RELNO** [comment]
@agrignard can you / @LAAP summarize these with numbers? "Cars %20 reduction" "bikes %15 Grow" etc. It's not super clear from the chart

**Comment by LAAP** [comment]
Sure. I will do that

**Comment by RELNO** [comment]
@LAAP can you share the numerical values of change for each of the 5 categories?

![image](https://user-images.githubusercontent.com/14296774/79671781-20e4c900-819b-11ea-80db-cea00a9a2f99.png)

**Comment by LAAP** [comment]
Ok, here is a "possible interpretations" for the stats that we will show. Since we have decided to show only 5 indicators, some other stats related to this 5 will be out of the visualization. Please let me know your thoughts (I have made also a pull request with the CSV file):


---

AFTER |   |   |   |  
-- | -- | -- | -- | --
  |   |   |   |  
CS Indicator | PCA deffinition |   |   |  
  |   |   |   |  
CARS | Cars | 33% |   |  
PEDESTRIANS | Pedestrians | 60% |   |  
BIKES | Shoft Mobility | 2% |   |  
PARKS | Open ground | 75500m2 |   |  
CULTURE | Augmented offer | 6 |   |  
  |   |   |   |  
  |   |   |   |  
BEFORE |   |   |   |  
  |   |   |   |  
CS Indicator | PCA deffinition |   |   | Impact in %
  |   |   |   |  
CARS | Cars | 16% |   | -51%
PEDESTRIANS | Pedestrians | 74% |   | 23%
BIKES | Shoft Mobility | 4% |   | 66%
PARKS | Open ground | 112400m2 | 49%
CULTURE | Augmented offer | 26 |   | 333%


In the jpg, just in case:

![Stats](https://user-images.githubusercontent.com/19315213/79765778-0d4d7580-82f5-11ea-9b24-3ec0025344a0.jpg)

**Comment by RELNO** [comment]
let's keep it open till it's implemented. 
Can you explain 

Before:
CULTURE | Augmented offer | 26 |   | 333% ?

What eventually is needed is a something like:
2020 - 25% more car emision

**Comment by LAAP** [comment]
We are visualizing PCA stats.

In terms of culture, the PCA doesn't have cultural elements 'per se', so I have use the the augmente offer of amenities (Mostly in restauration). I suggest to change the name from culture to "Usage" or "Amenities" or "Restauration":

<img width="1440" alt="stats1" src="https://user-images.githubusercontent.com/19315213/79775756-b64e9d00-8302-11ea-90fe-bd472824b403.png">

![stats2](https://user-images.githubusercontent.com/19315213/79775782-be0e4180-8302-11ea-980f-2d85e1f3d92b.png)

Since the increment is from 6 to 26, the increment is 433.3% (the PCA says 333%, I think that it is a typo...)

Regarding CO2 and emissions, yes, we can provide that number, but that is not only related to cars, it is output of the convinced effort of Cars, share vehicles, bikes, and pedestrians.... So, in order to avoid confusion, I think that it is better to trigger the % of reduction or increment of the number of cars, bikes, pedestrians... in each tag, than the impact in CO2. I suggest to have a new tag with CO2, or to keep the energy bars where we can visualize CO2 and temperature:
<img width="1440" alt="stats3" src="https://user-images.githubusercontent.com/19315213/79776551-e8143380-8303-11ea-910d-962e4082f8e9.png">

**Comment by RELNO** [comment]
Ok, so can you
-  create a ~3-4 word sentence for each one of the 2040 layers that shows the gain/improvement
(i.e car layer: 35% reduction in cars)
-  create a ~3-4 word sentence for each one of the 2020 layers that shows the problems/issues of today (i.e on car layer: 10000 hours of traffic jams a year)

**Comment by LAAP** [comment]
Ok, here is the new stats.
Please let me know your thoughts. also, if @nayoub @Markus could help with the "typos", it could be great:


2020 |  
-- | --
  |  
Layer | Sentence
  |  
Car   layer: | 33% car based mobility and 318   670 gCO2/Km
Pedestrian   layer: | 60% pedestrian mobility and 257   000m² of Pedestrian pathwalk.
Bikes  layer: | 2% bike based mobility and 10   250 vehicles/h
Parks   layer: | 75 500m2 of open land of parks   and 35ºC sidewalk temperature.
Leisure   layer: | 6 types of leisure offer and 7   300 m² of Relaxation areas.
  |  
2040 |  
  |  
Car   layer: | 51% reduction in cars and 48%   reduction in air pollution
Pedestrian   layer: | 23% increase of pedestrian   mobility and a increase of 29% in Pedestrian pathwalk.
Bikes   layer: | 66% increase of bikes and 24%   reduction of vehicles/h
Parks   layer: | 49% increase of parks and 4ºC of   temperature reduction in sidewalk temperature.
Leisure   layer: | 20 new types of leisure offer   and an increase of 585% in Relaxation areas.

**Comment by RELNO** [comment]
@LAAP great!

**Comment by LAAP** [comment]
Ok. So I am closing the issue

**Comment by RELNO** [comment]
I'm using this as a to-do list, so please wait till this is implemented. Thanks!

**Comment by agrignard** [comment]
Ok great! @LAAP do you have all this map with the percentage before and after? If not I can reask it to PCA. 
The number looks ok I am but curious abotu this one
````
51% reduction in cars and 48% reduction in air pollution
````
but maybe

**Comment by LAAP** [comment]
@agrignard, I am using directly the Numbers from PCA:

<img width="1440" alt="Captura de pantalla 2020-04-21 a las 9 03 19" src="https://user-images.githubusercontent.com/19315213/79871557-84950f00-83b2-11ea-94cb-b33559e56546.png">

Zoom:

![Sin título](https://user-images.githubusercontent.com/19315213/79871596-937bc180-83b2-11ea-9ca4-9946de93a18e.png)

**Comment by agrignard** [comment]
OK cool if you have this map, it's then their number

**Comment by LAAP** [comment]
Yes, as I said yesterday to @RELNO , We are not making calculations, we are just visualizing the PCA data
